### ISSUE TITLE
Initial position issue

### ISSUE THREAD

**Issue by pronebird** [alex3165/react-mapbox-gl#134] opened 2017-02-23 20:17 UTC
Hi,

I see animation on first pass. `fitBounds` don't change. Why?

```js
const markerLocation = [ displayLocation[1], displayLocation[0] ]; // <lng>, <lat>

<ReactMapboxGl style="mapbox://styles/mapbox/dark-v9"
    accessToken={ accessToken }
    containerStyle={{ height: '100%' }} 
    interactive={ false }
    fitBounds={ this.getBounds(displayLocation) }
    fitBoundsOptions={ {offset: [0, -100]} }>
  <Layer type="symbol" id="marker" layout={{ 'icon-image': 'marker-15' }}>
    <Feature coordinates={ markerLocation } />
  </Layer>
</ReactMapboxGl>
```

Looking through the code but can't really figure out what's going on:
https://github.com/alex3165/react-mapbox-gl/blob/master/src/map.tsx#L140

PS: setting `center` breaks `fitBounds`.

**Comment by z0d14c** [comment] 2017-02-23 20:23
Is the problem seeing the animation? If so, try setting ```linear: true``` in your fitBoundsOptions.

**Comment by pronebird** [comment] 2017-02-23 20:24
The problem is that I don't want to animate on first pass when I set bounds in the very first time. It must be moving the map from some initial location but I never specify it.

**Comment by alex3165** [comment] 2017-02-23 21:09
@pronebird Can you show `this.getBounds` and `displayLocation `

**Comment by alex3165** [comment] 2017-02-23 21:15
Also what do you mean by: setting `center` breaks `fitBounds` can you explain ?

**Comment by pronebird** [comment] 2017-02-23 21:18
`getBounds` simply calculates bbox and `displayLocation` at the moment is hardcoded:

```js
  displayLocation() {
      return [40.706213526877455, -74.0044641494751]; // [<lat>, <lng>]
  }

  getBounds(center) {
    const ruler = cheapRuler(center[0], 'meters');
    const bbox = ruler.bufferPoint(center, 100000);
    return [ bbox[1], bbox[0], bbox[3], bbox[2] ]; // <lng>, <lat>, <lng>, <lat>
  }
```

If I set `center` then `fitBoundsOptions.offset` does not seem to be used at all.

**Comment by pronebird** [comment] 2017-02-23 21:34
I was able to workaround that by saving first location and feeding it on each render, basically at this point ReactMapboxGl thinks that `center` didn't change and let `fitBounds` animate as expected:

```
    let centerLocation;
    if(!this._centerLocation) {
      this._centerLocation = markerLocation;
      centerLocation = this._centerLocation;
    } else {
      centerLocation = this._centerLocation;
    }

   // ...

              <ReactMapboxGl style="mapbox://styles/mapbox/dark-v9"
                  center={ centerLocation }
                  accessToken={ accessToken }
                  containerStyle={{ height: '100%' }} 
                  interactive={ false }
                  fitBounds={ this.getBounds(displayLocation) }
                  fitBoundsOptions={ {offset: [0, -100]} }>
```

**Comment by alex3165** [comment] 2017-02-23 21:45
@pronebird Just doing some tests and indeed, if center is not specified the map will move to fit the bounds specified with fitBounds which seems to be an expected to me don't you think ? And indeed if you want to prevent this you have to specify the center of the map.

**Comment by alex3165** [comment] 2017-02-23 21:47
Maybe the expected behaviour if center is not specified would be to calculate a center from the given bounds and use this center as a default ?

**Comment by pronebird** [comment] 2017-02-23 21:51
It feels to me that if I solely work with bounds then initial centering should somehow be adopted from supplied bounds.

**Comment by alex3165** [comment] 2017-02-23 21:53
Yep seems reasonable, I will publish a patch with the update

**Comment by alex3165** [comment] 2017-02-23 22:36
@pronebird Patch `1.3.1` include the update, let me know if it solve your problem so that I can close this issue

**Comment by pronebird** [comment] 2017-02-23 23:57
Thanks! I will check it in the morning.

**Comment by pronebird** [comment] 2017-02-24 11:42
Hmmmm

```
Uncaught Error: Invalid LngLat object: (NaN, NaN)
    at new LngLat (lng_lat.js:26)
    at Function.LngLat.convert (lng_lat.js:91)
    at e.i.jumpTo (camera.js:375)
    at new e (map.js:187)
    at ReactMapboxGl.componentDidMount (map.tsx:144)
```

I only provide `fitBounds` and `fitBoundsOptions`

**Comment by pronebird** [comment] 2017-02-24 11:43
Ok providing `center` works as expected!

**Comment by alex3165** [comment] 2017-02-24 12:23
@pronebird Do you provide a valid `fitBounds` with `Float` instead of `NaN` object ? Do you still have the issue ?

**Comment by pronebird** [comment] 2017-02-24 12:31
`fitBounds` is `[17.17093821313498, 57.57270983240012, 18.966223386865018, 61.08593716759985]`. Looks correct to me.

```js
<ReactMapboxGl style="mapbox://styles/mapbox/dark-v9"
  accessToken={ accessToken }
  containerStyle={{ height: '100%' }} 
  fitBounds={ bounds }
  fitBoundsOptions={ {offset: [0, -100]} }>
```

**Comment by alex3165** [comment] 2017-02-24 12:38
Ok I will consider it fixed, if there is still a problem please open a new issue explaining your process to get this issue with an example.

**Closed by alex3165** 2017-02-24 12:38 UTC
Labels: bug

**Comment by pronebird** [comment] 2017-02-24 17:13
I think I figured out what's going on. I was giving it flat array of fitBounds, while it expected array of arrays. i.e. fixing bounds to `[ [a, b], [c, d] ]` did the trick, that's because cheapRuler returns `[w, s, e, n]`

**Comment by pronebird** [comment] 2017-03-03 12:24
While this issue has been resolved. `fitBounds` still animates on first pass. I solved that by disabling animation during first render: 

  constructor() {
    super();
    this.state = { isFirstPass: true };
  }

  componentDidMount() {
    this.setState({ isFirstPass: false });
  }

  componentWillUnmount() {
    this.setState({ isFirstPass: true });
  }

render() {
  mapBoundsOptions = { offset: [0, -100], animate: !this.state.isFirstPass };
  // ...
}
