### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by pronebird** [alex3165/react-mapbox-gl#140] opened 2017-02-27 11:05 UTC
I see a memory usage increase each time I move camera between two different location. Reloading browser window releases all memory, however even destroying `ReactMapboxGl` (not rendering it on page) does not release memory. 

Therefore I think there is a memory leak somewhere. Last time I checked when jumping between two locations it went up to 1GB or RAM usage. I don't think that it's GC that does not release memory, it looks to me that some resources are being accumulated each time I move the map. 

Now it can be issue with mapbox-gl or react-mapbox-gl itself, I am not sure about that.

**Comment by alex3165** [comment] 2017-02-27 11:27
thanks for reporting, I will investigate as soon as possible

**Comment by pronebird** [comment] 2017-02-27 12:43
Thanks. I am looking into this as well.

**Comment by philpl** [comment] 2017-02-27 15:03
@pronebird Can you create a minimal js fiddle/bin or sth to reproduce this? I don't see it on the currently deployed version on Alex's site. If it occurs with only basic React Mapbox GL components being used, it's unlikely to be caused by anything in here.

The only thing that comes to mind is the clustering, since it was added recently, but like I said, I don't have a reproducible environment right now ;)

**Comment by pronebird** [comment] 2017-02-28 21:04
@philpl I was able to reproduce the memory increase by switching between "All shapes" and "GEOJSON" many times on @alex3165 website. I went as far as 2GB of RAM before I gave up. Not exactly sure what causes this.

**Comment by z0d14c** [comment] 2017-03-17 07:17
Hi, we have also been having memory leak issues in our application although have not 100% pinned down the cause. will be investigating ASAP and will share any findings/fixes.

**Comment by alex3165** [comment] 2017-03-20 09:16
I have created a simple boilerplate, if you guys manage to reproduce the issue using it https://github.com/alex3165/react-mapbox-gl-debug, it is a first good start on investigating what is happening

**Comment by pronebird** [comment] 2017-03-20 13:07
@alex3165 sorry for a dull report. Of course I will make a test case to reproduce this. Thanks again for making a debug boilerplate to make it easier!

**Comment by pronebird** [comment] 2017-03-24 19:01
@alex3165 @z0d14c 

I've created a simple test case which allows to observe certain growth in memory usage. It's a fairly simple scenario that we have in our app. We move the camera between two locations and change between two fixed zoom levels. All of that is done by calculating map bounds with cheap ruler.

Memory usage on page load is about 280M. After flying the map between two markers for 5 to 10 minutes I ended up with over 900M of memory usage.

I understand that it takes a lot of memory to display the map, but I would assume that if I had two fixed locations with two fixed zoom levels then at some point the memory consumption should stabilize after all tiles are cached in memory.

This is just my first observation with new debug boilerplate by @alex3165. I am not able to pinpoint it to anything yet.

<img width="1389" alt="screenshot 2017-03-24 18 58 01" src="https://cloud.githubusercontent.com/assets/704044/24309505/fcb1d6cc-10c3-11e7-8535-2b63bb9132e6.png">

**Comment by z0d14c** [comment] 2017-04-05 19:28
thanks @pronebird. this is pretty concerning. i hope to find some time to work on this and a few other issues with the library, but I will admit I'm not 100% sure where to start with this.

**Comment by daredevil82** [comment] 2017-07-22 11:34
To add to @pronebird's report, I'd like to add my own experience.  Admittedly, this is a much more resource intensive example and is centered around clustering

The [institution_data.txt file](https://github.com/alex3165/react-mapbox-gl/files/1167318/institution_data.txt) attached here is a 2.7MB JSON file with the location coordinates of all institutions of higher education in the US. There are about 8000 locations there.  The format is 

    {
        "pk": 6278,
        "location_region": "Rocky Mountains (CO, ID, MT, UT, WY)",
        "locale": "Rural, Remote",
        "location": {
            "latitude": "48.53309",
            "longitude": "-108.78364"
        },
        "name": "Aaniiih Nakoda College",
        "web_address": "www.ancollege.edu"
    }

The data takes about three seconds to retrieve from a cache.  It isn't in a very usable format, so I use the following to load and transform:

    transformData(data) {
        let transformed = [];
        
        data.forEach(e => {
            transformed.push({
                lat: e.location.latitude,
                lng: e.location.longitude,
                options: {
                    title: e.name,
                    web: e.web_address
                }
            });
        });
        
        console.log(`Transformed ${transformed.length} of ${data.length} records`);
        return transformed;
    }
    
    componentDidMount() {
        console.info('Starting request for geo data');
        const req = Institution.getAllGeo();
        
        req
            .then(data => {
                console.info('Received institution geo data');
                console.log(data);
                this.setState({
                    data: this.transformData(data)
                })
            })
            .catch(err => {
                console.error('Error retrieving institution geo data');
                console.error(err);
            })
    }

which is then rendered with the following:

    clusterMarker = (coordinates, pointCount) => (
        <Marker
            coordinates={coordinates}
            className="clusterMarker"
        >
            <div>{pointCount}</div>
        </Marker>
    );
    
    render() {
        return(
            <ReactMapboxGL
                style={this.state.mapStyle}
                accessToken={MAPBOX_API_TOKEN}
                containerStyle={this.state.viewport.containerStyle}
                center={this.state.viewport.center}
                zoom={this.state.viewport.zoom}
            >
                <Cluster ClusterMarkerFactory={this.clusterMarker} 
                         clusterThreshold={64}>
                    {
                        this.state.data.map((location, key) => {
                            console.log(`Rendering marker at ${location}`);

                            return <Marker
                                key={key}
                                coordinates={[location.lng, location.lat]}
                                className="marker"
                            />
                        })
                    }
                </Cluster>
            
            </ReactMapboxGL>
        )
    }

Once the clusters start processing, the map becomes entirely unresponsive for a time, and then has a severe lag throughout.

<img width="1161" alt="mapbox-gl-resource-usage" src="https://user-images.githubusercontent.com/1406974/28490746-a8d4600c-6eaf-11e7-8a48-4455cc94ab87.png">

The points of interest here are the `React App` and `GPU Process` tabs.  I'm running this on a maxed out 2013 MBP on latest Chrome.  While I admit this is an extreme case and I probably should use server side clustering or reduce the data set size, I feel this is a good stress test for any future potential solutions on this issue.

**Comment by alex3165** [comment] 2017-08-24 08:28
Hey everyone, it is been a long time since this issue hasn't been updated. Although with react-mapbox-gl v2 I potentially fix some memory leaks issues and mapbox-gl itself fixed some too so it is unlikely this issue is relevant anymore. If so feel free to open a new issue with some more explanations.

**Closed by alex3165** 2017-08-24 08:28 UTC
Labels: bug, priority ++
