### ISSUE TITLE
Scroll zoom over marker, popup, etc doesn't work

### ISSUE THREAD

**Issue by n23daniel** [alex3165/react-mapbox-gl#490] opened 2018-01-06 15:38 UTC
I'm using a map with scrollZoom and if I try to scroll over a marker/popup it scrolls on the document, instead of the map. I guess it's because of the DOM structure. Do you have an idea how this issue could be fixed? Thanks!

**Comment by alex3165** [comment] 2018-01-08 21:19
Hi @n23daniel I will close this issue as it is a duplicate of https://github.com/alex3165/react-mapbox-gl/issues/217 there is no good solution to go around this problem for now. Have a look at the thread in the other issue.

**Closed by alex3165** 2018-01-08 21:19 UTC
