### ISSUE TITLE
feature onClick vs onMouseEnter performance

### ISSUE THREAD

**Issue by texas697** [alex3165/react-mapbox-gl#197] opened 2017-04-18 14:43 UTC
I have setup my project using the london example. When I have 1000 features on the map the performance  of opening a popup is great. When I have 5,000 features the performance drops. I changed the popup to open onMouseEnter and it seems to work better. Is this correct? 

```
`  _handleMouseEnter(cursor, selectedMarker) {
    if (!this._drawActive) {
      this._allowPopup = true
      this._map.getCanvas().style.cursor = cursor
      this.props.setTimeout(() => { if (this._allowPopup) setMarker(selectedMarker) }, 1500)
    }
  }

  _handleMouseLeave(cursor) {
    if (!this._drawActive) {
      this._allowPopup = false
      this._map.getCanvas().style.cursor = cursor
      setMarker({})
    }
  }`
```
```
`  render() {
    const {
      offset
    } = this.state

    const {
      windowHeight,
      windowWidth,
      isSpinner,
      showTerritories,
      showActive,
      showBuiltout,
      showFuture,
      active,
      builtout,
      future,
      baseLayer,
      territoryCollection,
      territoryOptions,
      territoryBounds,
      selectedMarker,
      selectedTerritory
    } = this.props

    if (!_.isEmpty(territoryBounds)) {
      this._firstLoad = false
      return (
        <div className='animated fadeIn'>
          <ReactMapboxGl
            fitBounds={territoryBounds}
            interactive={!isSpinner}
            movingMethod='jumpTo'
            style={`mapbox://styles/mapbox/${baseLayer}-v9`}
            accessToken={config.mapboxToken}
            onStyleLoad={this._mapLoaded}
            onClick={() => {
              if (!this._drawActive) {
                setMarker({})
                setTerritory({ properties: {} })
              }
            }}
            onMove={this._coreLogic}
            containerStyle={{ height: windowHeight - 55, width: windowWidth - offset }}>
            <ScaleControl />
            <ZoomControl className='zoom-container' position='topLeft' />
            <LayerTerritories
              showTerritories={showTerritories}
              territoryCollection={territoryCollection}
              onClick={this._polygonClicked}
              onSelect={this._polygonSelect}
            />
            {selectedTerritory.properties.id && (
              <LayerSelectedTerritory selectedTerritory={selectedTerritory} />
            )}
            <LayerBuiltout
              showBuiltout={showBuiltout}
              builtout={builtout}
              onMouseEnter={(cursor, item) => this._handleMouseEnter(cursor, item)}
              onMouseLeave={cursor => this._handleMouseLeave(cursor)} />
            <LayerFuture
              showFuture={showFuture}
              future={future}
              onMouseEnter={(cursor, item) => this._handleMouseEnter(cursor, item)}
              onMouseLeave={cursor => this._handleMouseLeave(cursor)} />
            <LayerActive
              showActive={showActive}
              active={active}
              onMouseEnter={(cursor, item) => this._handleMouseEnter(cursor, item)}
              onMouseLeave={cursor => this._handleMouseLeave(cursor)} />
            {selectedMarker.id && (
              <LayerSelectedMarker selectedMarker={selectedMarker} />
            )}
            {(!_.isEmpty(selectedMarker) && !this._drawActive) && (
              <Popup
                coordinates={selectedMarker.position}
                anchor={'bottom'}
                offset={[0, -10]}>
                <SBDPopup
                  territoryOptions={territoryOptions}
                  selectedMarker={selectedMarker}
                  onChange={() => console.log('foo')}
                  handleShowConfirm={territoryId => this._handleShowConfirm(territoryId, selectedMarker)}
                />
              </Popup>
            )}
          </ReactMapboxGl>
          {isSpinner && (
            <div className='map-spinner-div'>
              <Spinner className='map-spinner' />
            </div>
          )}
      )
    } else
      return (
        <div className='animated fadeIn'>
          Loading...
        </div>
      )
  }`
```

Feature Layer
```
`class LayerActive extends Component {
  render() {
    return (
      <Layer
        type='circle'
        id='active'
        paint={{'circle-color': '#ff0007', 'circle-stroke-width': 2}}
        layout={{visibility: this.props.showActive}}>
        {this.props.active.map((item, index) => (
          <Feature
            key={item.id}
            coordinates={item.position}
            onMouseEnter={() => this.props.onMouseEnter('pointer', item)}
            onMouseLeave={() => this.props.onMouseLeave('')}/>
        )).toArray()}
      </Layer>
    )
  }
}

LayerActive.propTypes = {
  onMouseEnter: PropTypes.func,
  onMouseLeave: PropTypes.func,
  active: PropTypes.instanceOf(Immutable.List),
  showActive: PropTypes.string
}

export default LayerActive`
```

**Comment by alex3165** [comment] 2017-04-21 07:38
I don't see any reason why the performance would be better on mouse enter instead of on click event but if you can reproduce the problem using https://github.com/alex3165/react-mapbox-gl-debug I would be happy to have a look.

**Comment by jpdevries** [comment] 2017-06-19 01:10
I've upgraded from 1.12 to 2.0.3 and the `onMouseEnter` and other events seemed to have stopped working on my features. I noticed the london cycling example uses `onMouseEnter` but I haven't been able to run that example locally (typescript errors) and the demo site seems to be down.

Just curious if there were any breaking changes to `onMouseEnter` with Feature

**Comment by alex3165** [comment] 2017-06-19 06:22
I am not aware of any breaking changed on the `Feature` component and it seems to work on the examples: http://alex3165.github.io/react-mapbox-gl/

**Comment by jpdevries** [comment] 2017-06-19 14:24
I can't reproduce the issue I was having standalone. So it never happened ;)

**Comment by alex3165** [comment] 2017-06-19 14:38
Cool I will close this issue as v2 has lot of performance improvement for the events

**Closed by alex3165** 2017-06-19 14:38 UTC
Labels: To be defined
