### ISSUE TITLE
setState inside a onMouseEnter handler in feature

### ISSUE THREAD

**Issue by cyrilchapon** [alex3165/react-mapbox-gl#610] opened 2018-08-03 07:35 UTC
When setting state inside an `onMouseEnter` handler on a `Feature` does bug, it also triggers some `mouseLeave` events.

With this configuration

```
class MyMap extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
      locationHovered: false
    }
  }
  render () {
    return (
      <Map {...mapOptions}>
        <Layer {...layerOptions}>
          <Feature {...featureOptions}
            onMouseEnter={evt => {
              this.setState({ locationHovered: true })
            }}
            onMouseEnter={evt => {
              this.setState({ locationHovered: false })
            }}
          />

          {this.state.locationHovered &&
            <Popup
              {...popupOptions}
            >
          }
        </Layer>
      </Map>
    )
  }
}
```

The popup "flickers" as you enter or move on the marker.

EDIT : this doesn't seem to be the case on a `GeoJSONLayer`, but this is not an option for me, since I badly need the `draggable` functionality of `Feature`

EDIT : I should add that adding some `console.log`s inside handlers show erratics calls. Successive enter / leave

**Comment by rlueder** [comment] 2018-09-23 13:52
@cyrilchapon is it on purpose that your example has "onMouseEnter" twice? It's easy to imagine why it'd flicker if that's what you actually have in your application as onMouseEnter is firing multiple times and switching "locationHovered" between on and off constantly.

**Comment by daniel-hauser** [comment] 2019-01-06 17:45
@cyrilchapon, I want to close the issue if the problem was signing up to `onMouseEnter` and not `onMouseLeave`

**Comment by cyrilchapon** [comment] 2019-01-07 08:45
Hey @daniel-hauser .

To be perfectly honest, I needed a react binder for mapbox in a profesional project. That kind of small disappointments forced me to go uber/react-map-gl at that time. I might come back to alex3165/react-mapbox-gl for a future project.

**Comment by cyrilchapon** [comment] 2019-01-07 08:45
(And thus, cannot answer for now)

**Comment by daniel-hauser** [comment] 2019-01-07 10:07
I'm closing the issue for now, 
feel free to open a new one if the problem is not solved by changing `onMouseEnter` to `onMouseLeave`

**Closed by daniel-hauser** 2019-01-07 10:07 UTC
