### ISSUE TITLE
Feature Request: <Layer> Event handlers

### ISSUE THREAD

**Issue by stdmn** [alex3165/react-mapbox-gl#621] opened 2018-08-30 16:43 UTC
@mklopets Excited to see some new energy on this module.

I'd like to request that event handlers be added to the Layer module. I believe it should be possible to just crib the event handlers from the GeoJSONLayer module and include an map.on and map.off event handler for each layer. 

Happy to walk through what I did on the old version of the layer.js file to get this functionality.

**Comment by mklopets** [comment] 2018-08-31 12:27
I understand you already have some code for this somewhere? If that's the case, a PR would be very nice.

**Comment by stdmn** [comment] 2018-08-31 13:40
I have it for an older version (when it was in JS). Will see if I can recreate on the new version in TS.

**Comment by mklopets** [comment] 2018-08-31 14:37
Thanks!

**Comment by mklopets** [comment] 2018-09-01 20:43
Closing this to minimise noise as it's a duplicate of #563, but a PR is still very much welcome!

**Closed by mklopets** 2018-09-01 20:43 UTC
