### ISSUE TITLE
Feature onClick handler fires multiple times

### ISSUE THREAD

**Issue by daviestar** [alex3165/react-mapbox-gl#36] opened 2016-07-08 11:00 UTC
Hey again,

A mapbox [`click` event handler](https://github.com/alex3165/react-mapbox-gl/blob/master/src/layer.js#L157) is added to the map for each Layer in the map component, which results in the event getting fired as many times as you have Layer components.

Also [here](https://github.com/alex3165/react-mapbox-gl/blob/master/src/layer.js#L88-L98), the same Feature onClick handlers are fired for every feature found on the map under the click point.  

Combined, the poor handler is fired loads :)

Will post back with how I fix it for my use case.  I've got a PoC needing finished and an impending deadline-of-doom, but if I've time in the future I'll reference these issues in PRs. Cheers.

**Comment by daviestar** [comment] 2016-07-08 15:25
Ok, here's how I got the Feature onClick handler to only fire once, and only pickup the top-most feature you clicked on.  This is super messy and just a mad rush to get it working with no thought given to much else :)

I had to give all my layers sequential IDs in the JSX, I used format `100m-layer-n`.  And I removed [this line](https://github.com/alex3165/react-mapbox-gl/blob/master/src/layer.js#L157). 

In map.js:
```javascript
map.on("click", evt => {
  const children = [].concat(this.props.children);

  // find the 'id' prop of all layers in component
  let ids = [];
  for(const layer of children) {
    if(layer instanceof Array) {
      for(const subLayer of layer) {
        if(subLayer.props.id !== undefined) {
          ids.push(subLayer.props.id);
        }
      }
    } else {
      if(layer.props.id !== undefined) {
        ids.push(layer.props.id);
      }
    }
  }

  // find features from layers under click
  const features = map.queryRenderedFeatures(evt.point, { layers: ids });

  // find highest layer on z-index
  let highestLayerKey = -Infinity;
  let highestLayerFeatures = [];
  for(const feature of features) {
    const key = parseInt(feature.layer.id.replace('110m-layer-', ''));
    if(key >= highestLayerKey) {
      highestLayerKey = key;
      highestLayerFeatures.push(feature);
    }
  }

  // find highest feature in layer
  let highestFeatureKey = -Infinity;
  let highestFeature = false;
  for(const feature of highestLayerFeatures) {
    const id = feature.properties.id;
    if(id > highestFeatureKey) {
      highestFeatureKey = id;
      highestFeature = feature;
    }
  }
  if(!highestFeature) return;

  // find out which react layer the highest feature is in
  const layerId = highestFeature.layer.id;
  let activeLayer = false;
  for(const layer of children) {
    if(layer instanceof Array) {
      for(const subLayer of layer) {
        if(subLayer.props.id === layerId) {
          activeLayer = subLayer;
        }
      }
    } else {
      if(layer.props.id === layerId) {
        activeLayer = layer;
      }
    }
  }

  // find the react version of the feature, so we can grab the onClick handler
  const { properties } = highestFeature;
  const child = activeLayer.props.children[properties.id];
  const onClick = child && child.props.onClick;
  onClick && onClick({
    ...evt,
    highestFeature,
    map
  });
  // if (onClick) {
  //   onClick(map, ...args);
  // }
});
```

**Comment by alex3165** [comment] 2016-08-04 16:00
Hi @daviestar I have checked your issue but :

- I think that having a click event handler on every layer is not the best but it doesn't seems wrong neither to me. We can avoid attaching event handlers to the map for every layer if in the handler of the map component we trigger the `onclick` method of the children layer component, would it be a solution for you ?

- "Also here, the same Feature onClick handlers are fired for every feature found on the map under the click point." --> I think this is a totally expected behaviour, we want to trigger onClick handler if user click on the feature, what do you expect on this one ?

**Comment by daviestar** [comment] 2016-08-09 10:04
Hi @alex3165, thanks for your response.

> in the handler of the map component we trigger the onclick method of the children layer component

Yes, that sounds like the solution to me.. this is more or less what I have done, but I'm sure with your knowledge of React you can do it in only a couple of lines! 👍 

> we want to trigger onClick handler if user click on the feature, what do you expect on this one ?

Please have a look at my prototype project for a real-world example [here](http://100m.dstar.me/trip/S68XSxER).  I have 2 different click handlers - one for locations (circles), and one for journeys (polylines).  

Lets start with a 'normal' case of Mumbai, India.  This location has 2 different polylines under it - where the previous journey ends and the next journey begins.  Before my fix above, when clicking on this location, 1 location handler would be fired, as well as 2x journey handler (then those 3 events would be fired 8x for each layer on the map, as we discuss in the first point).

In my opinion, when dealing with 'top-down' style handlers `click`, `tap` etc., the intuitive thing would be to take z-index into account and only fire the event on the top-most feature clicked on.  And of course once per click.

A special case would be Bangkok, Thailand on my map.  It's hard to tell just now, but there are actually 4 locations here on top of one another since this location was visited multiple times.  Here, it would be useful to grab all those Features, but I would suggest you wouldn't want to fire 4x events, but rather 1x event and provide an array of 4x features.  You can see in my code above I pass parameter `highestFeature` and also `features` (all features) with the click event at the bottom.

Cheers.

**Comment by philpl** [comment] 2016-10-30 22:24
I don't think this is more sensible, give or take. I don't believe we wanted to introduce z-indices to the Layers, since that would add some complexity, that is really not necessary.

For overlaying features, it is a good idea to just deduplicate the data before rendering, and not after the events trigger.

We never intended the Map's onClick handler to be used in a preprocessed way. It should only ever be a proxy to the map's click event.

The layer's individual onClick event could just carry all features, instead of firing for each feature separately, that is true, but changing that introduces a breaking change, that by now would involve too much of a hassle for the community. If more people complain about the behaviour here, we will revisit it.

> I have 2 different click handlers - one for locations (circles), and one for journeys (polylines).

Take your example, assuming that every location is deduped, either you can attach onClick handlers to two layers and handle multiple onClicks outside of react-mapbox-gl, or write a custom onClick handler that attaches to the Map component. I think, that is not too bad.

Sorry, for not replying on this. We didn't consider this a priority, but I think we should close this for now. Please reopen this, if the project should revisit it.

**Closed by philpl** 2016-10-30 22:24 UTC
Labels: enhancement
