### ISSUE TITLE
symbolOnClick not working

### ISSUE THREAD

**Issue by redixhumayun** [alex3165/react-mapbox-gl#485] opened 2017-12-26 07:34 UTC
Hi, 

I have the following code 

```
<div>
        <GeoJSONLayer data={data}
                    id={'source_id_'+index}
                    key={index}
                    sourceOptions={{
                        cluster: true, 
                        clusterRadius: 50
                    }}
                    symbolOnClick={(evt) => console.log(evt)} />
        <Layer id={'cluster_layer_'+index}
                sourceId={'source_id_'+index}
                layerOptions={{
                    filter: [
                        'has', 'point_count'
                    ]
                }}
                layout={{ 'icon-image': 'myHydrantImage' }}
                images={images}
                type='symbol' />
    </div>
```

I am trying to cluster layers using the GeoJSONLayer and Layer components. The issue I am having is that the symbolOnClick event does not seem to be firing for the GeoJSONLayer. 

It seems to work fine when I am using circles for styling the data points, but not for the symbol. Any idea why?

**Comment by alex3165** [comment] 2018-01-09 13:26
Hi @redixhumayun it should be working, can you please replicate your issue using the webpackbin boilerplate linked in the readme? Thanks.

**Comment by kLaukkane** [comment] 2018-02-26 09:48
I'm having the same issue. I have pinpointed it happening with mapbox-gl 0.44.0 (react-mapbox-gl version does not seem to matter) but not with mapbox-gl 0.43.0. I will try to replicate the problem using the boilerplate later this week.

To clarify, the symbolOnClick doesn't seem to be completely broken, but rather really inconsistent. If you click the symbol five times, you usually get the event, but it seems to be completely random.

**Comment by kLaukkane** [comment] 2018-04-24 06:55
Finally got some time to dig into this. I'm not really sure if this is related to the OP, since I am using just normal layer and symbol features, but there's certainly going on with the onClick.

[Here's](https://github.com/kLaukkane/react-mapbox-gl-debug.git) my fork where the problem is reproduced on the boilerplate. 

The problem seems to happen when using mapbox-gl 0.44.0 (so it might be unrelated to react-mapbox-gl), and when there are frequent updates to React State (in my example, I'm updating the state with Date.now() every second). The state update seems to break the onClick from time to time; after a while it starts working again, and after new state update it doesn't. I think the problem can be worked around by optimizing state updates, but considering that it worked before, I think that it could be fixed on either mapbox-gl or react-mapbox-gl too.

**Comment by daniel-hauser** [comment] 2019-01-04 13:23
Closing the issue since `react-mapbox-gl` is now using `mapbox-gl@0.51.0` and the `symbolOnClick ` event now works in the [fork](https://github.com/kLaukkane/react-mapbox-gl-debug.git) @kLaukkane created

**Closed by daniel-hauser** 2019-01-04 13:23 UTC
Labels: To be defined
