### ISSUE TITLE
Canvas Size issues

### ISSUE THREAD

**Issue by andreas-koch** [alex3165/react-mapbox-gl#372] opened 2017-09-25 20:19 UTC
Hi, 
Im my code  I have the following structure
```
<div>
<some other div>
<the map>
</div>
```
"Some other div" is sometimes there and sometimes not. In one case the map gets 50% for the containerStyle and in the other case 100%.
The initial rendering is always correct. When "some other div" is not rendered the <div class="mapboxgl-map" updates correctly, but the canvas still got the old width. When I slightly change the window size, the canvas updates to the correct value.
Do you have any hint on how to force the canvas to update.

Thanks
Andreas

**Comment by alex3165** [comment] 2017-09-27 08:16
Hi @andreas-koch could you reproduce the issue with the [webpackbin template](https://www.webpackbin.com/bins/-KqtJN-qkLs4BPaVX0QS)

**Comment by andreas-koch** [comment] 2017-09-27 15:43
Hi,
honestly I could not. 
Using map.resize() in componentDidUpdate of the parent component fixes the issue. 

The div with class mapboxgl-map always did update correctly. But in the dev tools of chrom I could see that the canvas still had old values for width and height. Not really sure right now, what causes the issue.

Thanks,
Andreas

**Comment by alex3165** [comment] 2017-09-30 07:42
Probably related to https://github.com/alex3165/react-mapbox-gl/issues/395

**Comment by alex3165** [comment] 2017-10-27 14:41
I will close this issue, please try to reproduce it and open a new issue if it is still a problem

**Closed by alex3165** 2017-10-27 14:41 UTC
Labels: To be defined

**Comment by dedan** [comment] 2018-08-16 12:05
@andreas-koch On what exactly are you calling `map.resize()`? I have the same issue

**Comment by mlg87** [comment] 2018-08-20 21:52
@dedan call it on the map that is passed to `onStyleLoad` (i suppose you could probably also do it in `componentDidMount` assuming you have a ref to the map and its defined). here is an example:

```js
render() {
  return (
    <ReactMapboxGlMap
      containerStyle={{ height: '100%', width: '100%' }}
      onStyleLoad={this.handleStyleLoad}
    />
  )
}

handleStyleLoad = map => (map.resize())
```

**Comment by dedan** [comment] 2018-08-21 06:28
Thank you very much!

**Comment by arjunsajeev** [comment] 2019-02-12 15:38
Thanks a lot @mlg87 

> @dedan call it on the map that is passed to `onStyleLoad` (i suppose you could probably also do it in `componentDidMount` assuming you have a ref to the map and its defined). here is an example:
> 
> ```js
> render() {
>   return (
>     <ReactMapboxGlMap
>       containerStyle={{ height: '100%', width: '100%' }}
>       onStyleLoad={this.handleStyleLoad}
>     />
>   )
> }
> 
> handleStyleLoad = map => (map.resize())
> ```

**Comment by grallm** [comment] 2020-05-16 09:19
I suggest doing it `onRender`, the resizing is faster and so, less visible
```jsx
onRender={(map): void => { map.resize() }}
```

**Comment by ollyde** [comment] 2021-02-14 13:03
> @dedan call it on the map that is passed to `onStyleLoad` (i suppose you could probably also do it in `componentDidMount` assuming you have a ref to the map and its defined). here is an example:
> 
> ```js
> render() {
>   return (
>     <ReactMapboxGlMap
>       containerStyle={{ height: '100%', width: '100%' }}
>       onStyleLoad={this.handleStyleLoad}
>     />
>   )
> }
> 
> handleStyleLoad = map => (map.resize())
> ```

For TS users what type is Map?

**Comment by ollyde** [comment] 2021-02-14 13:08
Found it, you need to install mapbox-gl types ``npm install @types/mapbox-gl``

Then the following.

```
import * as MapboxGl from 'mapbox-gl';

const handleStyleLoad = (map: MapboxGl.Map) => (map.resize())

onStyleLoad={handleStyleLoad}
```

**Comment by victcebesp** [comment] 2022-03-03 10:20
Hello guys! I am still having this issue and I am currently using version 7.0.7 from react-map-gl. The issue is that now the property onStyleLoad is not available on the react-map-gl Map so that is no longer a solution and the issue is still active. The rendered canvas is first rendered with an incorrect width and height. However, once I resize the window, it is correctly resized. Any clues?

Thanks!

**Comment by reiseankur** [comment] 2022-09-22 13:46
> Hello guys! I am still having this issue and I am currently using version 7.0.7 from react-map-gl. The issue is that now the property onStyleLoad is not available on the react-map-gl Map so that is no longer a solution and the issue is still active. The rendered canvas is first rendered with an incorrect width and height. However, once I resize the window, it is correctly resized. Any clues?
> 
> Thanks!

Did you get the solution??

**Comment by estebanlis** [comment] 2022-10-26 15:04
> Hello guys! I am still having this issue and I am currently using version 7.0.7 from react-map-gl. The issue is that now the property onStyleLoad is not available on the react-map-gl Map so that is no longer a solution and the issue is still active. The rendered canvas is first rendered with an incorrect width and height. However, once I resize the window, it is correctly resized. Any clues?
> 
> Thanks!

Did you get the solution??

**Comment by joel-daros** [comment] 2022-11-10 13:44
> Hello guys! I am still having this issue and I am currently using version 7.0.7 from react-map-gl. The issue is that now the property onStyleLoad is not available on the react-map-gl Map so that is no longer a solution and the issue is still active. The rendered canvas is first rendered with an incorrect width and height. However, once I resize the window, it is correctly resized. Any clues?
> 
> Thanks!

Try the `onRender` method:

```
<Map
    style={{width: '100vw', height: '100vh'}}
    initialViewState={{
        longitude: -122.4,
        latitude: 37.8,
        zoom: 14,
    }}
    mapStyle="mapbox://styles/mapbox/streets-v9"
    onRender={(event) => event.target.resize()}
>
... 
</Map>
```
