### ISSUE TITLE
map canvas size doesn't work correctly 

### ISSUE THREAD

**Issue by keown** [alex3165/react-mapbox-gl#130] opened 2017-02-21 22:57 UTC
```jsx
<ReactMapboxGl
  style="mapbox://styles/mapbox/streets-v8"
  accessToken="pk.eyJ1IjoiZmFicmljOCIsImEiOiJjaWc5aTV1ZzUwMDJwdzJrb2w0dXRmc2d0In0.p6GGlfyV-WksaDV_KdN27A"
  containerStyle={{
    height: "100%",
    width: "100%"
  }}
  center={center}
  zoom={zoom}
  onStyleLoad={(map)=>{this.setup(map)}}
  onMoveEnd={(map, event) => {this.onChange(map, event)}}>
  <ZoomControl/>
  {popupDom}
</ReactMapboxGl>
```
i need the map to fill completely the container but seems that regardless of how the map is initialized the canvas is always 300px height. calling a `map.resize()` in the `onStyleLoad` callback fix everything but it also trigger a move event. i don't really want this situation because i call an api every time the map moves to update some markers, so basically i have a double api call when the component is mounted. 
any ideas on how to avoid this? anyway great library @alex3165, you saved me a ton of work! :-)

**Comment by alex3165** [comment] 2017-02-22 09:15
Hey @keown, thanks for your support, I did some tests and I can't reproduce your issue, here is what I have tested:
```
<div style={{ width: '100vw', height: '100vh' }}>
<ReactMapboxGl containerStyle={{ width: '100%', height: '100%' }}>
...
</ReactMapboxGl>
</div>
```

This works fine so if you have a link to an example with your issue it would be easier for me to debug (JSFiddle or public git repository)

**Comment by alex3165** [comment] 2017-03-14 09:23
I will close this Issue as I am not able to reproduce it, @keown please open a new one with an example if the issue is still there.

**Closed by alex3165** 2017-03-14 09:23 UTC
Labels: bug, To be defined
