### ISSUE TITLE
setStyle not working properly

### ISSUE THREAD

**Issue by CraigglesO** [alex3165/react-mapbox-gl#451] opened 2017-11-18 11:16 UTC
Your code makes 100% sense. You check for a change in style prop and call map.setStyle acordingly.

However: when I change the style prop, it does not react properly. It goes back to the original zoom when loaded and after changing the style several times I get this:

```
Uncaught TypeError: Cannot read property 'hasTransition' of undefined
    at t.hasTransitions (mapbox-gl.js:374)
    at e._render (mapbox-gl.js:484)
```

but that issue does not exist for mapbox-gl docs:
https://www.mapbox.com/mapbox-gl-js/example/setstyle/

**Comment by alex3165** [comment] 2017-11-21 12:03
Hey @CraigglesO Thanks for reporting the issue, could you reproduce it with this template: https://www.webpackbin.com/bins/-KqtJN-qkLs4BPaVX0QS ? That would be very helpful

**Comment by Wykks** [comment] 2017-11-21 14:45
Probably unrelated but, I got this error while updating mapbox-gl to version 0.42.1 for ngx-mapbox-gl  (https://travis-ci.org/Wykks/ngx-mapbox-gl/jobs/304987117#L1499).
Because of a change inside mapbox-gl, now you need to wait for the `load` event before calling `addImage`.
Which component do you use ?

**Comment by alex3165** [comment] 2017-11-21 21:20
Look like this issue: https://github.com/mapbox/mapbox-gl-js/issues/5714 fix released with version 0.42.2 of mapbox-gl

**Comment by alex3165** [comment] 2017-11-21 21:52
react-mapbox-gl `3.2.0` require mapbox-gl `0.42.2` which fix your problem 👍

**Comment by alex3165** [comment] 2017-11-21 21:53
Although, let me know if you still have an issue

**Closed by alex3165** 2017-11-21 21:52 UTC
Labels: To be defined

**Comment by CraigglesO** [comment] 2017-11-24 17:50
Sorry guys! Github never updated me you guys were active on this thread!! :(

I appreciate all the links and support. I will review, make changes and see what happens!

Thanks so much! <3

**Comment by CraigglesO** [comment] 2017-11-24 18:19
Update - here is the issue!

The bug is gone, however it still zooms back out.

```
<Map
              style={styles[mapIndex]}
              onStyleLoad={this.onStyleLoad}
              containerStyle={{
                height: "100%",
                width: "100%"
              }}
              center={[-113, 39.5]}
              zoom={[5.1]}
            >
```

Add `center` and `zoom` and upon each style update, it goes back to that center and zoom.

is this a "bug" or should I have those properties update via state management?

**Comment by Wykks** [comment] 2017-11-24 18:31
If you pass center and zoom like that, you're creating a new ref of center and zoom for each render. You can put center and zoom inside the state for example.
