### ISSUE TITLE
Question: is there a way to translate the map?

### ISSUE THREAD

**Issue by bumbus** [alex3165/react-mapbox-gl#616] opened 2018-08-24 09:14 UTC
Hi there,
is there a way to get translated maps?

There exists this package: https://github.com/mapbox/mapbox-gl-language.

And it works with the standard mapbox-gl lib:

```
import mapboxgl from 'mapbox-gl';
import MapboxLanguage from '@mapbox/mapbox-gl-language';

const map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/streets-v9',
      center: MAP_DEFAULT_LOCATION,
      zoom: MAP_DEFAULT_ZOOM,
    });
map.addControl(new MapboxLanguage())
```

So is there a way to access the map and add the control some how?

Thanks for helping out!

**Comment by mklopets** [comment] 2018-08-24 09:30
Hi! This is a duplicate of https://github.com/alex3165/react-mapbox-gl/issues/605, please see the answer there.

**Closed by mklopets** 2018-08-24 09:30 UTC
